# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
